add documentation for accessing the cursor object and fix a few minor spelling errors
nackjicholson/aiosql pull request #49
Opened 2020-10-10 23:06 UTC by danmurphy1217

Hey @nackjicholson, I wrote the documentation for accessing the cursor object and included an example for accessing column names and using `.fetchall()` and `.fetchone()`. I also saw a few minor spelling errors on SQL query names (`get_greetings` instead of `get_all_greetings` and `get_world_by_name` instead of `get_worlds_by_name`). Let me know your thoughts and if there's anything else I should include. Thanks!

2020-10-19 16:17 UTC, nackjicholson requested changes
I want to take a moment to thank you for taking your time to help out and provide this documentation. I'm always amazed that people will jump in and help out with a small tool like this. Adding thoughtful documentation is a big help to people that find this lib and want to use it. Cheers!

Overall this is looking great, just some minor feedback before we make it live.

2020-10-19 23:12 UTC, danmurphy1217 commented
> I want to take a moment to thank you for taking your time to help out and provide this documentation. I'm always amazed that people will jump in and help out with a small tool like this. Adding thoughtful documentation is a big help to people that find this lib and want to use it. Cheers!
> 
> Overall this is looking great, just some minor feedback before we make it live.

Hey @nackjicholson, happy to help! I just committed the requested changes- things should be good to go now.

Any other documentation or issues that I could tackle next?

2020-10-20 15:55 UTC, nackjicholson approved these changes
Thank you!

2020-10-20 15:56 UTC, merged

2020-10-20 16:01 UTC, nackjicholson commented
> Any other documentation or issues that I could tackle next?

@danmurphy1217 The issues page is a good place to start. If you have other things you want to improve about documentation, please go ahead. I want it to be better, and I'm definitely not a great technical writer ;)

There is also this one https://github.com/nackjicholson/aiosql/issues/21 which is probably a deeper exploratory task. I don't even know where to start with it, learning about it and reporting back on feasibility for all db drivers would be useful.